def generate_explanation(final_is_ai, final_confidence, ml_is_ai, ml_confidence,
                          freq_prob, noise_prob, artifact_prob, metadata_reasons, ela_variance=0.0):
    """
    Returns a structured dict with plain-English signal cards.

    Rule: Signal cards are CONTEXTUALIZED to the final verdict.
    - If final = Real  → secondary signals that say "AI" are shown as "warn" with explanation
      (they hint at patterns that were overridden by the primary AI detector)
    - If final = AI    → secondary signals that say "Real" are shown as "warn"
    This prevents confusing red "AI Sign" cards on images already classified as Real.
    """
    pct    = round(final_confidence * 100, 1)
    ml_pct = round(ml_confidence * 100, 1)

    # ── Verdict headline ──────────────────────────────────────────────────────
    if final_is_ai:
        headline = "This image was most likely created by an AI tool."
        subline  = f"Our system is {pct}% confident this is not a real photograph."
    else:
        headline = "This image appears to be a real photograph."
        subline  = f"Our system is {pct}% confident this was taken by a camera, not generated by AI."

    signals = []

    # ── 1. AI Detection Model (primary — always shown) ────────────────────────
    if ml_is_ai:
        signals.append({
            "icon": "🤖", "label": "AI Detection Model", "status": "ai",
            "text": f"Our AI detection engine is {ml_pct}% sure this image was generated by a tool like Midjourney, DALL-E, or Stable Diffusion."
        })
    else:
        signals.append({
            "icon": "🤖", "label": "AI Detection Model", "status": "real",
            "text": f"Our AI detection engine examined the full image and is {ml_pct}% sure this is a genuine photograph."
        })

    # ── 2. ELA — Image Consistency ───────────────────────────────────────────
    if ela_variance > 300:
        if final_is_ai:
            signals.append({
                "icon": "🔍", "label": "Image Consistency Check", "status": "ai",
                "text": "Different parts of this image have very different compression patterns — like a patchwork of regions processed separately. This is a common sign of AI editing or inpainting."
            })
        else:
            signals.append({
                "icon": "🔍", "label": "Image Consistency Check", "status": "warn",
                "text": "The image shows uneven compression across regions, likely because it was re-saved or shared multiple times (e.g. WhatsApp, messaging apps). This alone is not a sign of AI."
            })
    elif ela_variance > 120:
        signals.append({
            "icon": "🔍", "label": "Image Consistency Check", "status": "warn",
            "text": "Slight compression differences found across regions. This is common in images that have been re-shared or downloaded from the web — not necessarily AI."
        })
    else:
        signals.append({
            "icon": "🔍", "label": "Image Consistency Check", "status": "real",
            "text": "The image is compression-consistent throughout — no signs of stitched or regenerated regions."
        })

    # ── 3. Noise Pattern ─────────────────────────────────────────────────────
    if noise_prob > 0.65:
        if final_is_ai:
            signals.append({
                "icon": "📷", "label": "Camera Noise Pattern", "status": "ai",
                "text": "This image lacks the natural grain you'd expect from a real camera. The texture is suspiciously smooth — a pattern common in AI-generated images."
            })
        else:
            signals.append({
                "icon": "📷", "label": "Camera Noise Pattern", "status": "warn",
                "text": "The image has unusually smooth texture. This can happen with high-quality lenses, heavy post-processing, or web compression — our primary AI model confirmed it's still real."
            })
    elif noise_prob < 0.35:
        signals.append({
            "icon": "📷", "label": "Camera Noise Pattern", "status": "real",
            "text": "Natural, camera-consistent grain was found throughout — this is what we expect from a real photo."
        })

    # ── 4. Frequency Pattern ─────────────────────────────────────────────────
    if freq_prob > 0.65:
        if final_is_ai:
            signals.append({
                "icon": "〰️", "label": "Hidden Pattern Scan", "status": "ai",
                "text": "The mathematical structure of this image reveals recurring periodic patterns — a fingerprint left by AI generation algorithms."
            })
        else:
            signals.append({
                "icon": "〰️", "label": "Hidden Pattern Scan", "status": "warn",
                "text": "Some periodic patterns were detected in the image's frequency structure. This can be caused by camera sensor grids, JPEG compression artefacts, or high-frequency textures — our AI model did not flag this as generated."
            })

    # ── 5. Metadata ───────────────────────────────────────────────────────────
    if metadata_reasons:
        has_camera = any(k in " ".join(metadata_reasons).lower() for k in ["camera", "gps", "make", "model", "date"])
        has_ai_tag = any(k in " ".join(metadata_reasons).lower() for k in ["midjourney", "stable", "dall", "ai generator"])
        if has_ai_tag:
            signals.append({
                "icon": "🏷️", "label": "File Metadata", "status": "ai",
                "text": "The hidden data inside this file contains an AI generator tag — direct proof this was created by an AI tool."
            })
        elif has_camera:
            signals.append({
                "icon": "🏷️", "label": "File Metadata", "status": "real",
                "text": "Camera metadata found (brand, model, timestamp, GPS). This is strong evidence the image was taken by a real camera."
            })
        else:
            signals.append({
                "icon": "🏷️", "label": "File Metadata", "status": "warn",
                "text": "No camera metadata found. Images shared via apps (WhatsApp, Instagram, Telegram) have this stripped automatically — it's not a sign of AI."
            })

    return {
        "headline": headline,
        "subline":  subline,
        "signals":  signals
    }
